from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional, Dict

class ChatMessageRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The chat message from the user. Must not be empty and cannot exceed 2000 characters."
    )
    history: Optional[List[Dict[str, str]]] = Field(
        default=None,
        description="Optional conversation history as a list of dicts: {'role': 'user'|'assistant', 'content': str}"
    )

class SourceCitation(BaseModel):
    title: str = Field(..., description="Title of the source document")
    organization: str = Field(..., description="Publishing organization (e.g., WHO, NHS)")
    url: str = Field(..., description="Official URL reference")
    topic: Optional[str] = Field(default=None, description="Topic classification of the source")

class ChatMessageResponse(BaseModel):
    response: str = Field(..., description="The grounded response text generated by the assistant")
    sources: List[SourceCitation] = Field(default=[], description="List of verified reference sources")

class IngestRequest(BaseModel):
    title: str = Field(..., min_length=1)
    content: str = Field(..., min_length=1)
    source: str = Field(..., min_length=1)
    url: str = Field(..., min_length=1)
    organization: str = Field(..., min_length=1)
    topic: str = Field(..., min_length=1)
    date: Optional[str] = None

class HealthResponse(BaseModel):
    status: str = Field(..., description="API health status")
    vector_store_loaded: bool = Field(..., description="Whether the vector database has loaded documents")
